## Pizza Sales Data Cleaning.

#### Importing Python libraries for data analysis.

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#### Importing pizza sales data into Python.

In [5]:
orders = pd.read_excel("Pizza Sales Data.xlsx")

#### Selecting top 5 rows in the data.

In [7]:
orders.head()

pizza_id  order_id  pizza_name_id  quantity  order_date order_time  \
0         1         1     hawaiian_m         1  01-01-2015   11:38:36   
1         2         2  classic_dlx_m         1  01-01-2015   11:57:40   
2         3         2  five_cheese_l         1  01-01-2015   11:57:40   
3         4         2    ital_supr_l         1  01-01-2015   11:57:40   
4         5         2     mexicana_m         1  01-01-2015   11:57:40   

   unit_price  total_price pizza_size pizza_category  \
0       13.25        13.25          M        Classic   
1       16.00        16.00          M        Classic   
2       18.50        18.50          L         Veggie   
3       20.75        20.75          L        Supreme   
4       16.00        16.00          M         Veggie   

                                   pizza_ingredients  \
0           Sliced Ham, Pineapple, Mozzarella Cheese   
1  Pepperoni, Mushrooms, Red Onions, Red Peppers,...   
2  Mozzarella Cheese, Provolone Cheese, Smoked Go...   
3  Calabrese Salami, Capocollo, Tomatoes, Red Oni...   
4  Tomatoes, Red Peppers, Jalapeno Peppers, Red O...   

                  pizza_name  
0         The Hawaiian Pizza  
1   The Classic Deluxe Pizza  
2      The Five Cheese Pizza  
3  The Italian Supreme Pizza  
4         The Mexicana Pizza

#### Getting info on the data.

In [9]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48620 entries, 0 to 48619
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   pizza_id           48620 non-null  int64  
 1   order_id           48620 non-null  int64  
 2   pizza_name_id      48620 non-null  object 
 3   quantity           48620 non-null  int64  
 4   order_date         48620 non-null  object 
 5   order_time         48620 non-null  object 
 6   unit_price         48620 non-null  float64
 7   total_price        48620 non-null  float64
 8   pizza_size         48620 non-null  object 
 9   pizza_category     48620 non-null  object 
 10  pizza_ingredients  48620 non-null  object 
 11  pizza_name         48620 non-null  object 
dtypes: float64(2), int64(3), object(7)
memory usage: 4.5+ MB


In [10]:
orders.columns

Index(['pizza_id', 'order_id', 'pizza_name_id', 'quantity', 'order_date',
       'order_time', 'unit_price', 'total_price', 'pizza_size',
       'pizza_category', 'pizza_ingredients', 'pizza_name'],
      dtype='object')

### 1. Removing duplicated rows.

In [12]:
orders.duplicated().sum()

0

In [13]:
orders["pizza_id"].nunique()

48620

In [14]:
orders.duplicated(subset = ['order_id', 'pizza_name_id', 'quantity', 'order_date',
       'order_time', 'unit_price', 'total_price', 'pizza_size',
       'pizza_category', 'pizza_ingredients', 'pizza_name']).sum()

0

### 2. Data formatting & standardisation.

In [16]:
orders["order_id"].sort_values().unique()

array([    1,     2,     3, ..., 21348, 21349, 21350], dtype=int64)

In [17]:
orders["pizza_name_id"].sort_values().unique()

array(['bbq_ckn_l', 'bbq_ckn_m', 'bbq_ckn_s', 'big_meat_s',
       'brie_carre_s', 'calabrese_l', 'calabrese_m', 'calabrese_s',
       'cali_ckn_l', 'cali_ckn_m', 'cali_ckn_s', 'ckn_alfredo_l',
       'ckn_alfredo_m', 'ckn_alfredo_s', 'ckn_pesto_l', 'ckn_pesto_m',
       'ckn_pesto_s', 'classic_dlx_l', 'classic_dlx_m', 'classic_dlx_s',
       'five_cheese_l', 'four_cheese_l', 'four_cheese_m',
       'green_garden_l', 'green_garden_m', 'green_garden_s', 'hawaiian_l',
       'hawaiian_m', 'hawaiian_s', 'ital_cpcllo_l', 'ital_cpcllo_m',
       'ital_cpcllo_s', 'ital_supr_l', 'ital_supr_m', 'ital_supr_s',
       'ital_veggie_l', 'ital_veggie_m', 'ital_veggie_s',
       'mediterraneo_l', 'mediterraneo_m', 'mediterraneo_s', 'mexicana_l',
       'mexicana_m', 'mexicana_s', 'napolitana_l', 'napolitana_m',
       'napolitana_s', 'pep_msh_pep_l', 'pep_msh_pep_m', 'pep_msh_pep_s',
       'pepperoni_l', 'pepperoni_m', 'pepperoni_s', 'peppr_salami_l',
       'peppr_salami_m', 'peppr_salami_s', 'prs

In [18]:
orders["quantity"].sort_values().unique()

array([1, 2, 3, 4], dtype=int64)

In [19]:
orders["order_date"].sort_values().unique()

array(['01-01-2015', '01-02-2015', '01-03-2015', '01-04-2015',
       '01-05-2015', '01-06-2015', '01-07-2015', '01-08-2015',
       '01-09-2015', '01-10-2015', '01-11-2015', '01-12-2015',
       '02-01-2015', '02-02-2015', '02-03-2015', '02-04-2015',
       '02-05-2015', '02-06-2015', '02-07-2015', '02-08-2015',
       '02-09-2015', '02-10-2015', '02-11-2015', '02-12-2015',
       '03-01-2015', '03-02-2015', '03-03-2015', '03-04-2015',
       '03-05-2015', '03-06-2015', '03-07-2015', '03-08-2015',
       '03-09-2015', '03-10-2015', '03-11-2015', '03-12-2015',
       '04-01-2015', '04-02-2015', '04-03-2015', '04-04-2015',
       '04-05-2015', '04-06-2015', '04-07-2015', '04-08-2015',
       '04-09-2015', '04-10-2015', '04-11-2015', '04-12-2015',
       '05-01-2015', '05-02-2015', '05-03-2015', '05-04-2015',
       '05-05-2015', '05-06-2015', '05-07-2015', '05-08-2015',
       '05-09-2015', '05-11-2015', '05-12-2015', '06-01-2015',
       '06-02-2015', '06-03-2015', '06-04-2015', '06-05

In [20]:
orders["order_time"].sort_values().unique()

array([datetime.time(9, 52, 21), datetime.time(10, 25, 19),
       datetime.time(10, 34, 34), ..., datetime.time(23, 5, 17),
       datetime.time(23, 5, 24), datetime.time(23, 5, 52)], dtype=object)

In [21]:
orders["order_datetime"] = pd.to_datetime(orders["order_date"] + " " + orders["order_time"].astype(str), format="%d-%m-%Y %H:%M:%S")

In [22]:
orders["order_datetime"]

0       2015-01-01 11:38:36
1       2015-01-01 11:57:40
2       2015-01-01 11:57:40
3       2015-01-01 11:57:40
4       2015-01-01 11:57:40
                ...        
48615   2015-12-31 21:23:10
48616   2015-12-31 21:23:10
48617   2015-12-31 21:23:10
48618   2015-12-31 22:09:54
48619   2015-12-31 23:02:05
Name: order_datetime, Length: 48620, dtype: datetime64[ns]

In [23]:
orders["unit_price"].sort_values().unique()

array([ 9.75, 10.5 , 11.  , 12.  , 12.25, 12.5 , 12.75, 13.25, 14.5 ,
       14.75, 15.25, 16.  , 16.25, 16.5 , 16.75, 17.5 , 17.95, 18.5 ,
       20.25, 20.5 , 20.75, 21.  , 23.65, 25.5 , 35.95])

In [24]:
orders["total_price"].sort_values().unique()

array([ 9.75, 10.5 , 11.  , 12.  , 12.25, 12.5 , 12.75, 13.25, 14.5 ,
       14.75, 15.25, 16.  , 16.25, 16.5 , 16.75, 17.5 , 17.95, 18.5 ,
       19.5 , 20.25, 20.5 , 20.75, 21.  , 22.  , 23.65, 24.  , 24.5 ,
       25.  , 25.5 , 26.5 , 29.  , 29.5 , 30.5 , 32.  , 32.5 , 33.  ,
       33.5 , 35.  , 35.9 , 35.95, 36.  , 37.  , 37.5 , 40.5 , 41.  ,
       41.5 , 47.3 , 48.  , 48.75, 49.5 , 50.25, 51.  , 55.5 , 61.5 ,
       62.25, 83.  ])

In [25]:
orders["pizza_size"].sort_values().unique()

array(['L', 'M', 'S', 'XL', 'XXL'], dtype=object)

In [26]:
orders["pizza_category"].sort_values().unique()

array(['Chicken', 'Classic', 'Supreme', 'Veggie'], dtype=object)

In [27]:
orders["pizza_ingredients"].sort_values().unique()

array(['?duja Salami, Pancetta, Tomatoes, Red Onions, Friggitello Peppers, Garlic',
       'Bacon, Pepperoni, Italian Sausage, Chorizo Sausage',
       'Barbecued Chicken, Red Peppers, Green Peppers, Tomatoes, Red Onions, Barbecue Sauce',
       'Brie Carre Cheese, Prosciutto, Caramelized Onions, Pears, Thyme, Garlic',
       'Calabrese Salami, Capocollo, Tomatoes, Red Onions, Green Olives, Garlic',
       'Capocollo, Red Peppers, Tomatoes, Goat Cheese, Garlic, Oregano',
       'Capocollo, Tomatoes, Goat Cheese, Artichokes, Peperoncini verdi, Garlic',
       'Chicken, Artichoke, Spinach, Garlic, Jalapeno Peppers, Fontina Cheese, Gouda Cheese',
       'Chicken, Pineapple, Tomatoes, Red Peppers, Thai Sweet Chilli Sauce',
       'Chicken, Red Onions, Red Peppers, Mushrooms, Asiago Cheese, Alfredo Sauce',
       'Chicken, Tomatoes, Red Peppers, Red Onions, Jalapeno Peppers, Corn, Cilantro, Chipotle Sauce',
       'Chicken, Tomatoes, Red Peppers, Spinach, Garlic, Pesto Sauce',
       'Coars

In [28]:
orders["pizza_ingredients"] = orders["pizza_ingredients"].str.replace("?","N")

In [29]:
orders["pizza_name"].sort_values().unique()

array(['The Barbecue Chicken Pizza', 'The Big Meat Pizza',
       'The Brie Carre Pizza', 'The Calabrese Pizza',
       'The California Chicken Pizza', 'The Chicken Alfredo Pizza',
       'The Chicken Pesto Pizza', 'The Classic Deluxe Pizza',
       'The Five Cheese Pizza', 'The Four Cheese Pizza',
       'The Greek Pizza', 'The Green Garden Pizza', 'The Hawaiian Pizza',
       'The Italian Capocollo Pizza', 'The Italian Supreme Pizza',
       'The Italian Vegetables Pizza', 'The Mediterranean Pizza',
       'The Mexicana Pizza', 'The Napolitana Pizza',
       'The Pepper Salami Pizza', 'The Pepperoni Pizza',
       'The Pepperoni, Mushroom, and Peppers Pizza',
       'The Prosciutto and Arugula Pizza', 'The Sicilian Pizza',
       'The Soppressata Pizza', 'The Southwest Chicken Pizza',
       'The Spicy Italian Pizza', 'The Spinach Pesto Pizza',
       'The Spinach Supreme Pizza', 'The Spinach and Feta Pizza',
       'The Thai Chicken Pizza', 'The Vegetables + Vegetables Pizza'],
    

### 3. Imputation of blank/null values

In [31]:
orders.isna().sum()

pizza_id             0
order_id             0
pizza_name_id        0
quantity             0
order_date           0
order_time           0
unit_price           0
total_price          0
pizza_size           0
pizza_category       0
pizza_ingredients    0
pizza_name           0
order_datetime       0
dtype: int64

## Pizza Sales Data Analysis.

#### 1. Total Revenue

In [34]:
orders["total_price"].sum()

817860.05

#### 2. Total Sales

In [36]:
orders["quantity"].sum()

49574

#### 3. Total Orders

In [38]:
orders["order_id"].nunique()

21350

#### 4. Average Order Value

In [40]:
(orders["total_price"].sum()/orders["order_id"].nunique()).round(2)

38.31

#### 5. Average Pizza Price

In [42]:
(orders["total_price"].sum()/orders["quantity"].sum()).round(2)

16.5

#### 6. Average Pizzas per Order

In [44]:
(orders["quantity"].sum()/orders["order_id"].nunique()).round(2)

2.32